
services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: awvx0563
      MYSQL_DATABASE: bioskop

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "2.0"
        reservations:
          memory: 512M
          cpus: "1.0"